### ISSUE TITLE
Push to CRAN 

### ISSUE THREAD

**Issue by lz100** [dreamRs/shinyparticles#6]
Hi dreamRs, 

Thanks for providing the R API for particlesJs. Is it possible to push it to CRAN so I can import this package to my pkg in a formal way?

Thanks

**Comment by pvictor** [comment]
Hi @lz100 ,

I have currently no plan to push this package on CRAN since it's purely decorative.
How do you use it ? Maybe you can include directly the JavaScript library ? I can help

Victor

**Comment by lz100** [comment]
Thanks @pvictor I tried to import it for my [bioconductor](https://www.bioconductor.org/) package and they don't allow import from a Github package. Just thought directly import from this package would be easier to use, but I have already changed to particle.js.
